package GUI;

import BL.MiniRegFormHandler;
import BL.NextOfKinHandler;
import BL.PatientsHandler;
import MODEL.Mini.*;
import MODEL.Patient.Patient;
import MODEL.Patient.Person;

/**
 *
 * @author Karlo
 */
public class ShowMiniRegistarForm extends javax.swing.JFrame {
    private int IDPatient;
    MiniRegFormHandler miniRegFormHandler=new MiniRegFormHandler();
    PatientsHandler patientsHandler=new PatientsHandler();
    NextOfKinHandler nextOfKinHandler=new NextOfKinHandler();

    /**
     * Creates new form ShowRegistarForm
     */
    public ShowMiniRegistarForm() {
        initComponents();
    }
    public ShowMiniRegistarForm(int idpatient) {
        initComponents();
        IDPatient=idpatient;
        showMiniReg();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JLabel();
        txtMiddleName = new javax.swing.JLabel();
        txtSurname = new javax.swing.JLabel();
        txtSex = new javax.swing.JLabel();
        txtBriefStatementOfComplaints = new javax.swing.JLabel();
        txtContactTelephone = new javax.swing.JLabel();
        txtNextOfKinFirstName = new javax.swing.JLabel();
        txtNextOfKinMiddleName = new javax.swing.JLabel();
        txtNextOfKinSurname = new javax.swing.JLabel();
        txtNextOfKinRelationship = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtRegDate = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtBirthDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Mini Registration Form");

        jLabel2.setText("First name:");

        jLabel3.setText("Middle name:");

        jLabel4.setText("Surname:");

        jLabel5.setText("Sex:");

        jLabel6.setText("Brief Statement of Complaints:");

        jLabel7.setText("Contact Telephone Number:");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Next of Kin");

        jLabel9.setText("First name:");

        jLabel10.setText("Middle name:");

        jLabel11.setText("Surname:");

        jLabel12.setText("Relationship:");

        txtFirstName.setText("jLabel13");

        txtMiddleName.setText("jLabel14");

        txtSurname.setText("jLabel15");

        txtSex.setText("jLabel16");

        txtBriefStatementOfComplaints.setText("jLabel17");

        txtContactTelephone.setText("jLabel18");

        txtNextOfKinFirstName.setText("jLabel19");

        txtNextOfKinMiddleName.setText("jLabel20");

        txtNextOfKinSurname.setText("jLabel21");

        txtNextOfKinRelationship.setText("jLabel22");

        jLabel13.setText("Reg. Date:");

        txtRegDate.setText("jLabel14");

        jLabel14.setText("Date of Birth:");

        txtBirthDate.setText("jLabel15");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8)
                            .addComponent(jLabel14))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNextOfKinRelationship)
                            .addComponent(txtNextOfKinSurname)
                            .addComponent(txtNextOfKinMiddleName)
                            .addComponent(txtNextOfKinFirstName)
                            .addComponent(txtContactTelephone)
                            .addComponent(txtBriefStatementOfComplaints)
                            .addComponent(txtSex)
                            .addComponent(txtSurname)
                            .addComponent(txtMiddleName)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFirstName)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(txtRegDate))
                            .addComponent(txtBirthDate))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFirstName)
                    .addComponent(jLabel13)
                    .addComponent(txtRegDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMiddleName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSurname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSex))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBirthDate)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBriefStatementOfComplaints)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtContactTelephone)
                    .addComponent(jLabel7))
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNextOfKinFirstName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNextOfKinMiddleName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNextOfKinSurname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtNextOfKinRelationship))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowMiniRegistarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowMiniRegistarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowMiniRegistarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowMiniRegistarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowMiniRegistarForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel txtBirthDate;
    private javax.swing.JLabel txtBriefStatementOfComplaints;
    private javax.swing.JLabel txtContactTelephone;
    private javax.swing.JLabel txtFirstName;
    private javax.swing.JLabel txtMiddleName;
    private javax.swing.JLabel txtNextOfKinFirstName;
    private javax.swing.JLabel txtNextOfKinMiddleName;
    private javax.swing.JLabel txtNextOfKinRelationship;
    private javax.swing.JLabel txtNextOfKinSurname;
    private javax.swing.JLabel txtRegDate;
    private javax.swing.JLabel txtSex;
    private javax.swing.JLabel txtSurname;
    // End of variables declaration//GEN-END:variables

    private void showMiniReg() {
        MiniRegForm miniRegForm=miniRegFormHandler.getMiniRegForm(IDPatient);
        Patient patient=patientsHandler.getPatient(IDPatient);
        NextOfKin nextOfKin=nextOfKinHandler.getNextOfKin(miniRegForm.getNextOfKinID());
        
        txtRegDate.setText(miniRegForm.getRegDate().toString());
        txtFirstName.setText(patient.getFirstName());
        txtMiddleName.setText(patient.getMidleName());
        txtSurname.setText(patient.getSurname());
        txtSex.setText(patient.getSex());
        txtBirthDate.setText(patient.getBirthDate().toString());
        txtBriefStatementOfComplaints.setText(miniRegForm.getBriefStatementOfComplaint());
        txtContactTelephone.setText(miniRegForm.getContactTelephone());
        
        txtNextOfKinFirstName.setText(nextOfKin.getFirstName());
        txtNextOfKinMiddleName.setText(nextOfKin.getMidleName());
        txtNextOfKinSurname.setText(nextOfKin.getSurname());
        txtNextOfKinRelationship.setText(nextOfKin.getRelationShip());
        
    }
}
