package GUI;

import BL.AdressHandler;
import BL.ComprehensiveRegFormHandler;
import BL.NextOfKinHandler;
import BL.PatientsHandler;
import MODEL.Adress.*;
import MODEL.Comprehensive.*;
import MODEL.Mini.NextOfKin;
import MODEL.Patient.*;
import java.util.List;

/**
 *
 * @author Karlo
 */
public class ShowComprehensiveRegForm extends javax.swing.JFrame {
    private int IDPatient;
    PatientsHandler patientsHandler=new PatientsHandler();
    ComprehensiveRegFormHandler comprehensiveRegFormHandler=new ComprehensiveRegFormHandler();
    ComprehensiveRegistrationForm comprehensiveRegistrationForm;
    AdressHandler adressHandler=new AdressHandler();
    NextOfKinHandler nextOfKinHandler=new NextOfKinHandler();
    List<States> statesLista=adressHandler.getAllStates();
    List<City> cityLista=adressHandler.getAllCitys();
    List<Street> streetLista=adressHandler.getAllStreets();

    /**
     * Creates new form ShowComprehensiveRegForm
     */
    public ShowComprehensiveRegForm() {
        initComponents();
    }
    public ShowComprehensiveRegForm(int idpatient) {
        initComponents();
        IDPatient=idpatient;
        comprehensiveRegistrationForm=comprehensiveRegFormHandler.getComprehensiveRegistrationFormForPatient(IDPatient);
        showDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JLabel();
        txtMiddleName = new javax.swing.JLabel();
        txtSurname = new javax.swing.JLabel();
        txtSex = new javax.swing.JLabel();
        txtBirthDate = new javax.swing.JLabel();
        txtRegDate = new javax.swing.JLabel();
        btnNextBasic = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtPresentState = new javax.swing.JLabel();
        txtPresentCity = new javax.swing.JLabel();
        txtPresentStreet = new javax.swing.JLabel();
        txtPresentDoorNo = new javax.swing.JLabel();
        txtPermanentState = new javax.swing.JLabel();
        txtPermanentCity = new javax.swing.JLabel();
        txtPermanentStreet = new javax.swing.JLabel();
        txtPermanentDoorNo = new javax.swing.JLabel();
        txtTelephone = new javax.swing.JLabel();
        txtMobile = new javax.swing.JLabel();
        txtPager = new javax.swing.JLabel();
        txtFax = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        btnNextContact = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        btnNextContactNextOfKin = new javax.swing.JButton();
        txtNextFirstName = new javax.swing.JLabel();
        txtNextMiddleName = new javax.swing.JLabel();
        txtNextSurname = new javax.swing.JLabel();
        txtRelationship = new javax.swing.JLabel();
        txtNextState = new javax.swing.JLabel();
        txtNextCity = new javax.swing.JLabel();
        txtNextStreet = new javax.swing.JLabel();
        txtNextDoorNo = new javax.swing.JLabel();
        txtNextTelephone = new javax.swing.JLabel();
        txtNextMobile = new javax.swing.JLabel();
        txtNextPager = new javax.swing.JLabel();
        txtNextFax = new javax.swing.JLabel();
        txtNextEmail = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txtPersonalDetailsMartial = new javax.swing.JLabel();
        txtPersonalDetailsNoDependents = new javax.swing.JLabel();
        txtPersonalDetailsHeight = new javax.swing.JLabel();
        txtPersonalDetailsWeight = new javax.swing.JLabel();
        txtPersonalDetailsBloodType = new javax.swing.JLabel();
        btnNextPersonal = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        txtOccupation = new javax.swing.JLabel();
        txtGrossAnnualIncome = new javax.swing.JLabel();
        txtProfessionNext = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        txtVegetarian = new javax.swing.JLabel();
        txtSmoker = new javax.swing.JLabel();
        txtConsumeAlcoholic = new javax.swing.JLabel();
        txtUseStimulants = new javax.swing.JLabel();
        txtConsumptionCoffe = new javax.swing.JLabel();
        txtConsumptionSoft = new javax.swing.JLabel();
        txtHaveRegularMeal = new javax.swing.JLabel();
        txtEatHome = new javax.swing.JLabel();
        txtAverageCigarets = new javax.swing.JLabel();
        txtAverageDrinks = new javax.swing.JLabel();
        txtNextLifestyle = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        txtStatementOfComplaint = new javax.swing.JLabel();
        txtHistoryOfPrevoiusTreatment = new javax.swing.JLabel();
        txtPhysicianHospitalTreatred = new javax.swing.JLabel();
        btnNextBasicComplaints = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        txtDiabetic = new javax.swing.JLabel();
        txtHypertensive = new javax.swing.JLabel();
        txtCardiacCondition = new javax.swing.JLabel();
        txtRespiratoryCondition = new javax.swing.JLabel();
        txtDigestiveCondition = new javax.swing.JLabel();
        txtOrthopedicCondition = new javax.swing.JLabel();
        txtMuscularCondition = new javax.swing.JLabel();
        txtNeurologicalCondition = new javax.swing.JLabel();
        txtKnownAllergies = new javax.swing.JLabel();
        txtKnownAdverseReactionToDrugs = new javax.swing.JLabel();
        txtMajorSurgeries = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Basic Details");

        jLabel2.setText("First name:");

        jLabel3.setText("Middle name:");

        jLabel4.setText("Surname:");

        jLabel5.setText("Sex:");

        jLabel6.setText("Date of Birth:");

        jLabel7.setText("Reg. Date:");

        txtFirstName.setText("jLabel8");

        txtMiddleName.setText("jLabel9");

        txtSurname.setText("jLabel10");

        txtSex.setText("jLabel11");

        txtBirthDate.setText("jLabel12");

        txtRegDate.setText("jLabel13");

        btnNextBasic.setText("Next");
        btnNextBasic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextBasicActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtMiddleName))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(55, 55, 55)
                                        .addComponent(txtFirstName)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(45, 45, 45)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBirthDate)
                                            .addComponent(txtSex)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(118, 118, 118)
                                        .addComponent(txtSurname)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRegDate)
                .addGap(114, 114, 114))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnNextBasic)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(txtFirstName)
                    .addComponent(txtRegDate))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMiddleName))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSurname))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSex))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBirthDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(btnNextBasic)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Basic Details", jPanel1);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("Contact Details");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Present Adress");

        jLabel10.setText("State:");

        jLabel11.setText("City:");

        jLabel12.setText("Street:");

        jLabel13.setText("Door No:");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("Permanent Adress");

        jLabel15.setText("State:");

        jLabel16.setText("City:");

        jLabel17.setText("Street:");

        jLabel18.setText("Door No:");

        jLabel19.setText("Telephone:");

        jLabel20.setText("Mobile:");

        jLabel21.setText("Pager:");

        jLabel22.setText("Fax:");

        jLabel23.setText("Email:");

        txtPresentState.setText("jLabel24");

        txtPresentCity.setText("jLabel25");

        txtPresentStreet.setText("jLabel26");

        txtPresentDoorNo.setText("jLabel27");

        txtPermanentState.setText("jLabel28");

        txtPermanentCity.setText("jLabel29");

        txtPermanentStreet.setText("jLabel30");

        txtPermanentDoorNo.setText("jLabel31");

        txtTelephone.setText("jLabel32");

        txtMobile.setText("jLabel33");

        txtPager.setText("jLabel34");

        txtFax.setText("jLabel35");

        txtEmail.setText("jLabel36");

        btnNextContact.setText("Next");
        btnNextContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextContactActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel18)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel12)
                                                    .addComponent(jLabel13))
                                                .addGap(200, 200, 200)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel19)
                                                    .addComponent(jLabel20)
                                                    .addComponent(jLabel21)
                                                    .addComponent(jLabel22)
                                                    .addComponent(jLabel23))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtEmail)
                                                    .addComponent(txtFax)
                                                    .addComponent(txtPager)
                                                    .addComponent(txtMobile)
                                                    .addComponent(txtTelephone)))))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtPresentState)
                                        .addComponent(jLabel14)
                                        .addComponent(txtPresentCity)
                                        .addComponent(txtPresentStreet)
                                        .addComponent(txtPresentDoorNo)
                                        .addComponent(txtPermanentState)
                                        .addComponent(txtPermanentCity)
                                        .addComponent(txtPermanentStreet)
                                        .addComponent(txtPermanentDoorNo)))))
                        .addGap(0, 306, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNextContact)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel19)
                    .addComponent(txtPresentState)
                    .addComponent(txtTelephone))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel20)
                    .addComponent(txtPresentCity)
                    .addComponent(txtMobile))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel21)
                    .addComponent(txtPresentStreet)
                    .addComponent(txtPager))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel22)
                    .addComponent(txtPresentDoorNo)
                    .addComponent(txtFax))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel23)
                    .addComponent(txtEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtPermanentState))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtPermanentCity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtPermanentStreet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtPermanentDoorNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNextContact)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Contact Details", jPanel2);

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel24.setText("Contact Next-of-Kin");

        jLabel25.setText("First name:");

        jLabel26.setText("Middle name:");

        jLabel27.setText("Surname:");

        jLabel28.setText("Relationship :");

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel29.setText("Contact Adress");

        jLabel30.setText("State:");

        jLabel31.setText("City:");

        jLabel32.setText("Street:");

        jLabel33.setText("Door No:");

        jLabel34.setText("Telephone:");

        jLabel35.setText("Mobile:");

        jLabel36.setText("Pager:");

        jLabel37.setText("Fax:");

        jLabel38.setText("Email:");

        btnNextContactNextOfKin.setText("Next");
        btnNextContactNextOfKin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextContactNextOfKinActionPerformed(evt);
            }
        });

        txtNextFirstName.setText("jLabel39");

        txtNextMiddleName.setText("jLabel40");

        txtNextSurname.setText("jLabel41");

        txtRelationship.setText("jLabel42");

        txtNextState.setText("jLabel43");

        txtNextCity.setText("jLabel44");

        txtNextStreet.setText("jLabel45");

        txtNextDoorNo.setText("jLabel46");

        txtNextTelephone.setText("jLabel47");

        txtNextMobile.setText("jLabel48");

        txtNextPager.setText("jLabel49");

        txtNextFax.setText("jLabel50");

        txtNextEmail.setText("jLabel51");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel24))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel26)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtNextMiddleName))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel27)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtNextSurname))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel25)
                                                .addGap(34, 34, 34)
                                                .addComponent(txtNextFirstName))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel33)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtNextDoorNo))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel32)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtNextStreet))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel31)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtNextCity))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel30)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtNextState))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel28)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtRelationship))))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel29)))
                                .addGap(99, 99, 99)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel36)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel37))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNextFax)
                                    .addComponent(txtNextPager)
                                    .addComponent(txtNextMobile)
                                    .addComponent(txtNextTelephone)
                                    .addComponent(txtNextEmail))))
                        .addGap(0, 311, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNextContactNextOfKin)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel34)
                    .addComponent(txtNextFirstName)
                    .addComponent(txtNextTelephone))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txtNextMiddleName))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(txtNextSurname))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(txtRelationship))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(jLabel37)
                            .addComponent(txtNextFax))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(txtNextState)
                            .addComponent(txtNextEmail)
                            .addComponent(jLabel38))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(txtNextCity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(txtNextStreet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(txtNextDoorNo)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(txtNextMobile))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNextPager)
                            .addComponent(jLabel36))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(btnNextContactNextOfKin)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Contact Next-of-Kin", jPanel3);

        jLabel39.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel39.setText("Personal Details");

        jLabel40.setText("Martial Status:");

        jLabel41.setText("No. of Dependents:");

        jLabel42.setText("Height:");

        jLabel43.setText("Weight:");

        jLabel44.setText("Blood Type:");

        txtPersonalDetailsMartial.setText("jLabel45");

        txtPersonalDetailsNoDependents.setText("jLabel46");

        txtPersonalDetailsHeight.setText("jLabel47");

        txtPersonalDetailsWeight.setText("jLabel48");

        txtPersonalDetailsBloodType.setText("jLabel49");

        btnNextPersonal.setText("Next");
        btnNextPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextPersonalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel39))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel41)
                                    .addComponent(jLabel42)
                                    .addComponent(jLabel43)
                                    .addComponent(jLabel44))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPersonalDetailsBloodType)
                                    .addComponent(txtPersonalDetailsWeight)
                                    .addComponent(txtPersonalDetailsHeight)
                                    .addComponent(txtPersonalDetailsNoDependents)
                                    .addComponent(txtPersonalDetailsMartial))))
                        .addGap(0, 482, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNextPersonal)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel39)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(txtPersonalDetailsMartial))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(txtPersonalDetailsNoDependents))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(txtPersonalDetailsHeight))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(txtPersonalDetailsWeight))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(txtPersonalDetailsBloodType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(btnNextPersonal)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Personal Details", jPanel4);

        jLabel45.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel45.setText("Profession Details");

        jLabel46.setText("Occupation:");

        jLabel47.setText("Gross Annual Income:");

        txtOccupation.setText("jLabel48");

        txtGrossAnnualIncome.setText("jLabel48");

        txtProfessionNext.setText("Next");
        txtProfessionNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessionNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel45))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel47)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtGrossAnnualIncome))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel46)
                                        .addGap(80, 80, 80)
                                        .addComponent(txtOccupation)))))
                        .addGap(0, 475, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtProfessionNext)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel45)
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(txtOccupation))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(txtGrossAnnualIncome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                .addComponent(txtProfessionNext)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Profession Details", jPanel5);

        jLabel48.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel48.setText("Lifestyle");

        jLabel49.setText("Vegetarian:");

        jLabel50.setText("Smoker:");

        jLabel51.setText("Consume Alcoholic Beverage:");

        jLabel52.setText("Use Stimulants:");

        jLabel53.setText("Consumption of Coffe-Tea per Day:");

        jLabel54.setText("Consumption of Soft Drinks per Day:");

        jLabel55.setText("Have Regular Meal (Breakfast/Lunch/Dinner):");

        jLabel56.setText("Eat Home Food Predominantly:");

        jLabel57.setText("Average No. of Cigarettes per Day:");

        jLabel58.setText("Average No. of Drinks per Day:");

        txtVegetarian.setText("jLabel59");

        txtSmoker.setText("jLabel60");

        txtConsumeAlcoholic.setText("jLabel61");

        txtUseStimulants.setText("jLabel62");

        txtConsumptionCoffe.setText("jLabel63");

        txtConsumptionSoft.setText("jLabel64");

        txtHaveRegularMeal.setText("jLabel65");

        txtEatHome.setText("jLabel66");

        txtAverageCigarets.setText("jLabel67");

        txtAverageDrinks.setText("jLabel68");

        txtNextLifestyle.setText("Next");
        txtNextLifestyle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNextLifestyleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel48))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel49)
                                    .addComponent(jLabel50)
                                    .addComponent(jLabel51)
                                    .addComponent(jLabel52)
                                    .addComponent(jLabel53)
                                    .addComponent(jLabel54)
                                    .addComponent(jLabel55)
                                    .addComponent(jLabel56)
                                    .addComponent(jLabel57)
                                    .addComponent(jLabel58))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAverageDrinks)
                                    .addComponent(txtAverageCigarets)
                                    .addComponent(txtEatHome)
                                    .addComponent(txtHaveRegularMeal)
                                    .addComponent(txtConsumptionSoft)
                                    .addComponent(txtConsumptionCoffe)
                                    .addComponent(txtUseStimulants)
                                    .addComponent(txtConsumeAlcoholic)
                                    .addComponent(txtSmoker)
                                    .addComponent(txtVegetarian))))
                        .addGap(0, 355, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtNextLifestyle)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel48)
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(txtVegetarian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(txtSmoker))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(txtConsumeAlcoholic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(txtUseStimulants))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(txtConsumptionCoffe))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel54)
                    .addComponent(txtConsumptionSoft))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(txtHaveRegularMeal))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(txtEatHome))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(txtAverageCigarets))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel58)
                    .addComponent(txtAverageDrinks))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(txtNextLifestyle)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lifestyle", jPanel6);

        jLabel59.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel59.setText("Basic Complaints");

        jLabel60.setText("Statement of Complaint:");

        jLabel61.setText("History of Previous Treatment:");

        jLabel62.setText("Physician/Hospital Treated:");

        txtStatementOfComplaint.setText("jLabel63");

        txtHistoryOfPrevoiusTreatment.setText("jLabel64");

        txtPhysicianHospitalTreatred.setText("jLabel65");

        btnNextBasicComplaints.setText("Next");
        btnNextBasicComplaints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextBasicComplaintsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel59))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel60)
                                    .addComponent(jLabel61)
                                    .addComponent(jLabel62))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPhysicianHospitalTreatred)
                                    .addComponent(txtHistoryOfPrevoiusTreatment)
                                    .addComponent(txtStatementOfComplaint))))
                        .addGap(0, 419, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNextBasicComplaints)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel59)
                .addGap(39, 39, 39)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel60)
                    .addComponent(txtStatementOfComplaint))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(txtHistoryOfPrevoiusTreatment))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel62)
                    .addComponent(txtPhysicianHospitalTreatred))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(btnNextBasicComplaints)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Basic Complaints", jPanel7);

        jLabel63.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel63.setText("Important Medical Complaints");

        jLabel64.setText("Diabetic:");

        jLabel65.setText("Hypertensive:");

        jLabel66.setText("Cardiac Condition:");

        jLabel67.setText("Respiratory Condition:");

        jLabel68.setText("Digestive Condition:");

        jLabel69.setText("Orthopedic Condition:");

        jLabel70.setText("Muscular Condition:");

        jLabel71.setText("Neurological Condition:");

        jLabel72.setText("Known Allergies:");

        jLabel73.setText("Known Adverse Reaction to Specific Drugs:");

        jLabel74.setText("Major Surgeries (History):");

        txtDiabetic.setText("jLabel75");

        txtHypertensive.setText("jLabel76");

        txtCardiacCondition.setText("jLabel77");

        txtRespiratoryCondition.setText("jLabel78");

        txtDigestiveCondition.setText("jLabel79");

        txtOrthopedicCondition.setText("jLabel80");

        txtMuscularCondition.setText("jLabel81");

        txtNeurologicalCondition.setText("jLabel82");

        txtKnownAllergies.setText("jLabel83");

        txtKnownAdverseReactionToDrugs.setText("jLabel84");

        txtMajorSurgeries.setText("jLabel85");

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel65)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtHypertensive))
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel64)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDiabetic))
                                .addComponent(txtCardiacCondition)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel72)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel67)
                                            .addComponent(jLabel68)
                                            .addComponent(jLabel69)
                                            .addComponent(jLabel70))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMuscularCondition)
                                            .addComponent(txtOrthopedicCondition)
                                            .addComponent(txtDigestiveCondition)
                                            .addComponent(txtRespiratoryCondition)))))
                            .addComponent(jLabel66))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel73)
                                    .addComponent(jLabel74))
                                .addGap(79, 79, 79))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(183, 183, 183)
                                        .addComponent(txtKnownAdverseReactionToDrugs))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(185, 185, 185)
                                        .addComponent(txtMajorSurgeries)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel71)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKnownAllergies)
                            .addComponent(txtNeurologicalCondition))
                        .addContainerGap())))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel63)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel63)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel64)
                                    .addComponent(txtDiabetic)
                                    .addComponent(jLabel73))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel65)
                                    .addComponent(txtHypertensive))
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel66)
                                            .addComponent(txtCardiacCondition)))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel74))))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(txtKnownAdverseReactionToDrugs)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel67)
                            .addComponent(txtRespiratoryCondition)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(txtMajorSurgeries)))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel68)
                    .addComponent(txtDigestiveCondition))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel69)
                    .addComponent(txtOrthopedicCondition))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel70)
                    .addComponent(txtMuscularCondition))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel71)
                    .addComponent(txtNeurologicalCondition))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel72)
                    .addComponent(txtKnownAllergies))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Important Medical Complaints", jPanel8);

        getContentPane().add(jTabbedPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextBasicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextBasicActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnNextBasicActionPerformed

    private void btnNextContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextContactActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnNextContactActionPerformed

    private void btnNextContactNextOfKinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextContactNextOfKinActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_btnNextContactNextOfKinActionPerformed

    private void btnNextPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextPersonalActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_btnNextPersonalActionPerformed

    private void txtProfessionNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessionNextActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_txtProfessionNextActionPerformed

    private void txtNextLifestyleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNextLifestyleActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(6);
    }//GEN-LAST:event_txtNextLifestyleActionPerformed

    private void btnNextBasicComplaintsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextBasicComplaintsActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(7);
    }//GEN-LAST:event_btnNextBasicComplaintsActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowComprehensiveRegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowComprehensiveRegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowComprehensiveRegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowComprehensiveRegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowComprehensiveRegForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnNextBasic;
    private javax.swing.JButton btnNextBasicComplaints;
    private javax.swing.JButton btnNextContact;
    private javax.swing.JButton btnNextContactNextOfKin;
    private javax.swing.JButton btnNextPersonal;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel txtAverageCigarets;
    private javax.swing.JLabel txtAverageDrinks;
    private javax.swing.JLabel txtBirthDate;
    private javax.swing.JLabel txtCardiacCondition;
    private javax.swing.JLabel txtConsumeAlcoholic;
    private javax.swing.JLabel txtConsumptionCoffe;
    private javax.swing.JLabel txtConsumptionSoft;
    private javax.swing.JLabel txtDiabetic;
    private javax.swing.JLabel txtDigestiveCondition;
    private javax.swing.JLabel txtEatHome;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtFax;
    private javax.swing.JLabel txtFirstName;
    private javax.swing.JLabel txtGrossAnnualIncome;
    private javax.swing.JLabel txtHaveRegularMeal;
    private javax.swing.JLabel txtHistoryOfPrevoiusTreatment;
    private javax.swing.JLabel txtHypertensive;
    private javax.swing.JLabel txtKnownAdverseReactionToDrugs;
    private javax.swing.JLabel txtKnownAllergies;
    private javax.swing.JLabel txtMajorSurgeries;
    private javax.swing.JLabel txtMiddleName;
    private javax.swing.JLabel txtMobile;
    private javax.swing.JLabel txtMuscularCondition;
    private javax.swing.JLabel txtNeurologicalCondition;
    private javax.swing.JLabel txtNextCity;
    private javax.swing.JLabel txtNextDoorNo;
    private javax.swing.JLabel txtNextEmail;
    private javax.swing.JLabel txtNextFax;
    private javax.swing.JLabel txtNextFirstName;
    private javax.swing.JButton txtNextLifestyle;
    private javax.swing.JLabel txtNextMiddleName;
    private javax.swing.JLabel txtNextMobile;
    private javax.swing.JLabel txtNextPager;
    private javax.swing.JLabel txtNextState;
    private javax.swing.JLabel txtNextStreet;
    private javax.swing.JLabel txtNextSurname;
    private javax.swing.JLabel txtNextTelephone;
    private javax.swing.JLabel txtOccupation;
    private javax.swing.JLabel txtOrthopedicCondition;
    private javax.swing.JLabel txtPager;
    private javax.swing.JLabel txtPermanentCity;
    private javax.swing.JLabel txtPermanentDoorNo;
    private javax.swing.JLabel txtPermanentState;
    private javax.swing.JLabel txtPermanentStreet;
    private javax.swing.JLabel txtPersonalDetailsBloodType;
    private javax.swing.JLabel txtPersonalDetailsHeight;
    private javax.swing.JLabel txtPersonalDetailsMartial;
    private javax.swing.JLabel txtPersonalDetailsNoDependents;
    private javax.swing.JLabel txtPersonalDetailsWeight;
    private javax.swing.JLabel txtPhysicianHospitalTreatred;
    private javax.swing.JLabel txtPresentCity;
    private javax.swing.JLabel txtPresentDoorNo;
    private javax.swing.JLabel txtPresentState;
    private javax.swing.JLabel txtPresentStreet;
    private javax.swing.JButton txtProfessionNext;
    private javax.swing.JLabel txtRegDate;
    private javax.swing.JLabel txtRelationship;
    private javax.swing.JLabel txtRespiratoryCondition;
    private javax.swing.JLabel txtSex;
    private javax.swing.JLabel txtSmoker;
    private javax.swing.JLabel txtStatementOfComplaint;
    private javax.swing.JLabel txtSurname;
    private javax.swing.JLabel txtTelephone;
    private javax.swing.JLabel txtUseStimulants;
    private javax.swing.JLabel txtVegetarian;
    // End of variables declaration//GEN-END:variables

    private void showDetails() {
        showBasicDetails();
        showContactDetails();
        showContactNextOfKin();
        showPersonalDetails();
        showProfessionDetails();
        showLifestyle();
        showBasicComplaints();
        showImportantMedicalComplaits();
    }

    private void showBasicDetails() {
        Patient p=patientsHandler.getPatient(IDPatient);
        txtFirstName.setText(p.getFirstName());
        txtMiddleName.setText(p.getMidleName());
        txtSurname.setText(p.getSurname());
        txtSex.setText(p.getSex());
        txtBirthDate.setText(p.getBirthDate().toString());
        txtRegDate.setText(comprehensiveRegistrationForm.getRegDate().toString());
    }

    private void showContactDetails() {
        ContactDetails c=comprehensiveRegFormHandler.getContactDetails(comprehensiveRegistrationForm.getContactDetailsID());
        Adress presentAdress=adressHandler.getAdress(c.getAdressPresentID());
        txtPresentState.setText(adressHandler.getStates(presentAdress.getStateID()).toString().toString());
        txtPresentCity.setText(adressHandler.getCity(presentAdress.getCityID()).toString());
        txtPresentStreet.setText(adressHandler.getStreet(presentAdress.getStreetID()).toString());
        txtPresentDoorNo.setText(presentAdress.getDoorNo());
        
        Adress permnenantAdress=adressHandler.getAdress(c.getAdressPermenantID());
        txtPermanentState.setText(adressHandler.getStates(permnenantAdress.getStateID()).toString());
        txtPermanentCity.setText(adressHandler.getCity(permnenantAdress.getCityID()).toString());
        txtPermanentStreet.setText(adressHandler.getStreet(permnenantAdress.getStreetID()).toString());
        txtPermanentDoorNo.setText(permnenantAdress.getDoorNo());
        
        ElectronicContact electronicContact=comprehensiveRegFormHandler.getElectronicContact(c.getElectronicContactID());
        txtTelephone.setText(electronicContact.getTelephone());
        txtMobile.setText(electronicContact.getMobile());
        txtPager.setText(electronicContact.getPager());
        txtFax.setText(electronicContact.getFax());
        txtEmail.setText(electronicContact.getEmail());
    }

    private void showContactNextOfKin() {
        ContactNextOfKin cnok=comprehensiveRegFormHandler.getContactNextOfKin(comprehensiveRegistrationForm.getContactNextOfKinID());
        NextOfKin nextOfKin=nextOfKinHandler.getNextOfKin(cnok.getNextOfKinID());
        txtNextFirstName.setText(nextOfKin.getFirstName());
        txtNextMiddleName.setText(nextOfKin.getMidleName());
        txtNextSurname.setText(nextOfKin.getSurname());
        txtRelationship.setText(nextOfKin.getRelationShip());
        
        Adress adress=adressHandler.getAdress(cnok.getAdressID());
        txtNextState.setText(adressHandler.getStates(adress.getStateID()).toString());
        txtNextCity.setText(adressHandler.getCity(adress.getCityID()).toString());
        txtNextStreet.setText(adressHandler.getStreet(adress.getStreetID()).toString());
        txtNextDoorNo.setText(adress.getDoorNo());
        
        ElectronicContact electronicContact=comprehensiveRegFormHandler.getElectronicContact(cnok.getElectronicContactID());
        txtNextTelephone.setText(electronicContact.getTelephone());
        txtNextMobile.setText(electronicContact.getMobile());
        txtNextPager.setText(electronicContact.getPager());
        txtNextFax.setText(electronicContact.getFax());
        txtEmail.setText(electronicContact.getEmail());
    }

    private void showPersonalDetails() {
        PersonalDetails personalDetails=comprehensiveRegFormHandler.getPersonalDetails(comprehensiveRegistrationForm.getPersonalDetailsID());
        txtPersonalDetailsMartial.setText(setBoolText(personalDetails.getMartialStatus()));
        txtPersonalDetailsNoDependents.setText(personalDetails.getNoOfDependets()+"");
        txtPersonalDetailsHeight.setText(personalDetails.getHeightPerson()+"");
        txtPersonalDetailsWeight.setText(personalDetails.getWeightPerson()+"");
        txtPersonalDetailsBloodType.setText(personalDetails.getBloodType());
    }
    
    private String setBoolText(boolean tvrdnja){
        if (tvrdnja) {
            return "Yes";
        }else
            return "No";
    }

    private void showProfessionDetails() {
        ProfessionDetails p=comprehensiveRegFormHandler.getProfessionDetails(comprehensiveRegistrationForm.getProfessionDetailsID());
        txtOccupation.setText(p.getOccupation());
        txtGrossAnnualIncome.setText(p.getGrossAnnualIncome()+"");
    }

    private void showLifestyle() {
        LifeStyle l=comprehensiveRegFormHandler.getLifeStyle(comprehensiveRegistrationForm.getLifeStyleID());
        txtVegetarian.setText(setBoolText(l.getVegetarian()));
        txtSmoker.setText(setBoolText(l.getSmoker()));
        txtConsumeAlcoholic.setText(setBoolText(l.getConsumeAlcohol()));
        txtUseStimulants.setText(setBoolText(l.getUseStimulants()));
        txtConsumptionCoffe.setText(l.getConsumptionOfCoffeTeaPerDay()+"");
        txtConsumptionSoft.setText(l.getConsumptionOfSoftDrinksPerDay()+"");
        txtHaveRegularMeal.setText(setBoolText(l.getRegularMeals()));
        txtEatHome.setText(setBoolText(l.getEatHomePredominantly()));
        txtAverageCigarets.setText(l.getCigaretsPerDay()+"");
        txtAverageDrinks.setText(l.getDrinksPerDay()+"");
    }

    private void showBasicComplaints() {
        BasicComplaints b=comprehensiveRegFormHandler.getBasicComplaints(comprehensiveRegistrationForm.getBasicComplaintsID());
        txtStatementOfComplaint.setText(b.getStateOfComplaints());
        txtHistoryOfPrevoiusTreatment.setText(b.getHistoryOfPreviouseTreatment());
        txtPhysicianHospitalTreatred.setText(b.getHospitalLastTreated());
    }

    private void showImportantMedicalComplaits() {
        ImportantMedicalComplaints i=comprehensiveRegFormHandler.getImportantMedicalComplaints(comprehensiveRegistrationForm.getImportantMedicalComplaintsID());
        txtDiabetic.setText(setBoolText(i.getDiabetic()));
        txtHypertensive.setText(setBoolText(i.getHypertensive()));
        txtCardiacCondition.setText(setBoolText(i.getCardiacCondition()));
        txtRespiratoryCondition.setText(setBoolText(i.getRespiratoryCondition()));
        txtDigestiveCondition.setText(setBoolText(i.getDigestiveCondition()));
        txtOrthopedicCondition.setText(setBoolText(i.getOrthopedicCondition()));
        txtMuscularCondition.setText(setBoolText(i.getMuscularCondition()));
        txtNeurologicalCondition.setText(setBoolText(i.getNeurologicalCondition()));
        txtKnownAllergies.setText(i.getKnownAlergies());
        txtKnownAdverseReactionToDrugs.setText(i.getKnownReactionToDrugs());
        txtMajorSurgeries.setText(i.getMajorSurgeries());
    }

}
